In [1]:
# import necessary module packages
from bokeh.io import output_file, show
from bokeh.plotting import figure
import pandas as pd

In [3]:
# reading our crash file
df = pd.read_csv("./data/transbase_collisions.csv")
# df.head()

In [4]:
# get unique collision category
collision_type = df["type_of_collision"].unique()
collision_type.sort()

In [5]:
years = df["accident_year"].unique()
years.sort()
years = years.astype(str).tolist()

In [6]:
# groupby the dataset using accident_year and type_of_collision. This would return a dataset, convert the dataset into list
df2=df.groupby(["accident_year","type_of_collision"]).sum()[["number_killed","number_injured"]].reset_index()
# df2

In [7]:
df2["number_killed"][df2["accident_year"]==2014].tolist()

[5, 2, 2, 1, 3, 0, 0, 1, 17]

In [8]:
collisions = collision_type.tolist()
y2014 = df2["number_killed"][df2["accident_year"]==2014].tolist()
y2015 = df2["number_killed"][df2["accident_year"]==2015].tolist()
y2016 = df2["number_killed"][df2["accident_year"]==2016].tolist()
y2017 = df2["number_killed"][df2["accident_year"]==2017].tolist()
y2018 = df2["number_killed"][df2["accident_year"]==2018].tolist()

In [9]:
output_file("bar_stacked.html")
data = {'collisions' : collisions,
        '2014'   : y2014,
        '2015'   : y2015,
        '2016'   : y2016,
        '2017'   : y2017,
        '2018'   : y2018}

colors = ["#FFC0CB", "#6A5ACD", "#DC143C","#FF8C00","#32CD32"]

In [10]:
p = figure(x_range=collisions, plot_width=1000, plot_height=500, title="Fatality Counts by Collision Type",
           toolbar_location=None, tools="hover", tooltips="$name @collisions: @$name")
p.vbar_stack(years, x='collisions', width=0.7, color=colors, source=data, legend=[(str(x)+str(" ")) for x in years])

p.y_range.start = 0
p.x_range.range_padding = 0.0
p.xgrid.grid_line_color = None
p.axis.minor_tick_line_color = None
p.outline_line_color = None
p.legend.location = "top_left"
p.legend.orientation = "horizontal"

show(p)

In [11]:
#   cross check
df.groupby(["accident_year","type_of_collision"]).sum().number_killed

accident_year  type_of_collision
2014           Broadside              5
               Head-On                2
               Hit Object             2
               Not Stated             1
               Other                  3
               Overturned             0
               Rear End               0
               Sideswipe              1
               Vehicle/Pedestrian    17
2015           Broadside              6
               Head-On                3
               Hit Object             0
               Not Stated             0
               Other                  1
               Overturned             0
               Rear End               2
               Sideswipe              2
               Vehicle/Pedestrian    17
2016           Broadside              4
               Head-On                7
               Hit Object             0
               Not Stated             1
               Other                  0
               Overturned             0
               Rear End               0
               Sideswipe              1
               Vehicle/Pedestrian    15
2017           Broadside              3
               Head-On                1
               Hit Object             1
               Not Stated             2
               Other                  1
               Overturned             0
               Rear End               1
               Sideswipe              0
               Vehicle/Pedestrian    11
2018           Broadside              2
               Head-On                2
               Hit Object             2
               Not Stated             0
               Other                  0
               Overturned             0
               Rear End               1
               Sideswipe              1
               Vehicle/Pedestrian    15
Name: number_killed, dtype: int64

In [12]:
df.groupby(["accident_year","type_of_collision"]).sum().reset_index().number_killed

0      5
1      2
2      2
3      1
4      3
5      0
6      0
7      1
8     17
9      6
10     3
11     0
12     0
13     1
14     0
15     2
16     2
17    17
18     4
19     7
20     0
21     1
22     0
23     0
24     0
25     1
26    15
27     3
28     1
29     1
30     2
31     1
32     0
33     1
34     0
35    11
36     2
37     2
38     2
39     0
40     0
41     0
42     1
43     1
44    15
Name: number_killed, dtype: int64

In [13]:
df2["number_killed"][df2["accident_year"]==2014]

0     5
1     2
2     2
3     1
4     3
5     0
6     0
7     1
8    17
Name: number_killed, dtype: int64

In [14]:
df2

    accident_year   type_of_collision  number_killed  number_injured
0            2014           Broadside              5            1187
1            2014             Head-On              2             235
2            2014          Hit Object              2             107
3            2014          Not Stated              1              77
4            2014               Other              3             133
5            2014          Overturned              0              71
6            2014            Rear End              0             617
7            2014           Sideswipe              1             514
8            2014  Vehicle/Pedestrian             17             708
9            2015           Broadside              6            1218
10           2015             Head-On              3             236
11           2015          Hit Object              0             109
12           2015          Not Stated              0              81
13           2015               Other              1             163
14           2015          Overturned              0              57
15           2015            Rear End              2             686
16           2015           Sideswipe              2             522
17           2015  Vehicle/Pedestrian             17             664
18           2016           Broadside              4            1365
19           2016             Head-On              7             246
20           2016          Hit Object              0             141
21           2016          Not Stated              1             148
22           2016               Other              0             161
23           2016          Overturned              0              66
24           2016            Rear End              0             726
25           2016           Sideswipe              1             535
26           2016  Vehicle/Pedestrian             15             739
27           2017           Broadside              3            1358
28           2017             Head-On              1             278
29           2017          Hit Object              1             137
30           2017          Not Stated              2             163
31           2017               Other              1             191
32           2017          Overturned              0              47
33           2017            Rear End              1             758
34           2017           Sideswipe              0             559
35           2017  Vehicle/Pedestrian             11             762
36           2018           Broadside              2            1270
37           2018             Head-On              2             307
38           2018          Hit Object              2             130
39           2018          Not Stated              0             137
40           2018               Other              0             227
41           2018          Overturned              0              65
42           2018            Rear End              1             675
43           2018           Sideswipe              1             568
44           2018  Vehicle/Pedestrian             15             734